spring:
  #redis缓存配置
  cache:
    type: REDIS
  redis:
    host: localhost
    password: 123456
    database: 1
    port: 6379
    timeout: 5000ms
    pool:
      max-idle: 8 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      #sentinel:
      #master: mymaster # 哨兵监听的Redis server的名称
      #nodes:
      #127.0.0.1:26379,127.0.0.1:26479,127.0.0.1:26579 #哨兵的配置列表